if ( WIN32 )
    if(${CMAKE_SYSTEM_VERSION} EQUAL 6.1)
        add_definitions(-DNTDDI_VERSION=NTDDI_WIN7)
        add_definitions(-D_WIN32_WINNT=_WIN32_WINNT_WIN7)
    elseif(${CMAKE_SYSTEM_VERSION} EQUAL 6.2)
        add_definitions(-DNTDDI_VERSION=NTDDI_WIN8)
        add_definitions(-D_WIN32_WINNT=_WIN32_WINNT_WIN8)
    elseif(${CMAKE_SYSTEM_VERSION} EQUAL 10)
        add_definitions(-DNTDDI_VERSION=NTDDI_WIN10)
        add_definitions(-D_WIN32_WINNT=_WIN32_WINNT_WIN10)
    endif()
endif()

if (MINGW)
    set(CMAKE_RC_COMPILER_INIT windres)
    ENABLE_LANGUAGE(RC)
    SET(CMAKE_RC_COMPILE_OBJECT
            "<CMAKE_RC_COMPILER> <FLAGS> -O coff <DEFINES> -i <SOURCE> -o <OBJECT>")
endif ()